In [1]:
import numpy as np
from scipy.optimize import linear_sum_assignment

cost = np.array([[4, 1, 3], [2, 0, 5], [3, 2, 2]])
row_ind, col_ind = linear_sum_assignment(cost)
print(row_ind)  #开销矩阵对应的行索引
print(col_ind)  #对应行索引的最优指派的列索引
print(cost[row_ind, col_ind])  #提取每个行索引的最优指派列索引所在的元素，形成数组
print(cost[row_ind, col_ind].sum())  #数组求和

[0 1 2]
[1 0 2]
[1 2 2]
5


In [2]:
def check(x):
    if x.sum() > 400:
        return False
    if x[0] + 2 * x[1] + 2 * x[2] + x[3] + 6 * x[4] > 800:
        return False
    if 2 * x[0] + x[1] + 6 * x[2] > 200:
        return False
    if x[2] + x[3] + 5 * x[3] > 200:
        return False

    return True


def get_radom():
    x = np.random.randint(100, size=5)
    while not check(x):
        x = get_radom()
    return x


lim = 10 ** 6
ans = -1

for i in range(lim):
    num = get_radom()
    ans = max(ans, num.all())
    if i % 10000 == 0:
        print(i)

print('ans=' + ans)

0
10000
20000
30000
40000
50000
60000
70000
80000
90000
100000
110000
120000
130000
140000
150000
160000
170000
180000
190000
200000
210000
220000
230000
240000
250000
260000
270000
280000
290000
300000
310000
320000
330000
340000
350000
360000
370000
380000
390000
400000
410000
420000
430000
440000
450000
460000
470000
480000
490000
500000
510000
520000
530000
540000
550000
560000
570000
580000
590000
600000
610000
620000
630000
640000
650000
660000
670000
680000
690000
700000
710000
720000
730000
740000
750000
760000
770000
780000
790000
800000
810000
820000
830000
840000
850000
860000
870000
880000
890000
900000
910000
920000
930000
940000
950000
960000
970000
980000
990000


TypeError: can only concatenate str (not "numpy.bool_") to str