In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.loadtxt("data14_1_1.txt")
a

array([[2.0e+00, 1.5e+03, 2.0e+04, 5.5e+06, 5.0e-01, 1.0e+00],
       [2.5e+00, 2.7e+03, 1.8e+04, 6.5e+06, 3.0e-01, 5.0e-01],
       [1.8e+00, 2.0e+03, 2.1e+04, 4.5e+06, 7.0e-01, 7.0e-01],
       [2.2e+00, 1.8e+03, 2.0e+04, 5.0e+06, 5.0e-01, 5.0e-01]])

In [3]:
b = np.linalg.norm(a, axis=0)
b

array([4.28135493e+00, 4.09633983e+03, 3.95600809e+04, 1.08512672e+07,
       1.03923048e+00, 1.41067360e+00])

In [4]:
m1 = a.max(axis=0)
m2 = a.min(axis=0)
m1, m2

(array([2.5e+00, 2.7e+03, 2.1e+04, 6.5e+06, 7.0e-01, 1.0e+00]),
 array([1.8e+00, 1.5e+03, 1.8e+04, 4.5e+06, 3.0e-01, 5.0e-01]))

In [5]:
R1 = a / b
R1

array([[0.46714184, 0.36618056, 0.50556014, 0.50685325, 0.48112522,
        0.70888121],
       [0.58392729, 0.659125  , 0.45500413, 0.59900838, 0.28867513,
        0.3544406 ],
       [0.42042765, 0.48824074, 0.53083815, 0.41469811, 0.67357531,
        0.49621684],
       [0.51385602, 0.43941667, 0.50556014, 0.46077568, 0.48112522,
        0.3544406 ]])

In [6]:
R2 = a / m1
R2

array([[0.8       , 0.55555556, 0.95238095, 0.84615385, 0.71428571,
        1.        ],
       [1.        , 1.        , 0.85714286, 1.        , 0.42857143,
        0.5       ],
       [0.72      , 0.74074074, 1.        , 0.69230769, 1.        ,
        0.7       ],
       [0.88      , 0.66666667, 0.95238095, 0.76923077, 0.71428571,
        0.5       ]])

In [7]:
R3 = (a - m2) / (m1 - m2)
R3

array([[0.28571429, 0.        , 0.66666667, 0.5       , 0.5       ,
        1.        ],
       [1.        , 1.        , 0.        , 1.        , 0.        ,
        0.        ],
       [0.        , 0.41666667, 1.        , 0.        , 1.        ,
        0.4       ],
       [0.57142857, 0.25      , 0.66666667, 0.25      , 0.5       ,
        0.        ]])

In [8]:
R1[:, 3] = 1 - a[:, 3] / b[3]
R2[:, 3] = m2[3] / a[:, 3]
R3[:, 3] = (m1[3] / a[:, 3]) / (m1[3] - m2[3])

In [9]:
R1

array([[0.46714184, 0.36618056, 0.50556014, 0.49314675, 0.48112522,
        0.70888121],
       [0.58392729, 0.659125  , 0.45500413, 0.40099162, 0.28867513,
        0.3544406 ],
       [0.42042765, 0.48824074, 0.53083815, 0.58530189, 0.67357531,
        0.49621684],
       [0.51385602, 0.43941667, 0.50556014, 0.53922432, 0.48112522,
        0.3544406 ]])

In [10]:
R2

array([[0.8       , 0.55555556, 0.95238095, 0.81818182, 0.71428571,
        1.        ],
       [1.        , 1.        , 0.85714286, 0.69230769, 0.42857143,
        0.5       ],
       [0.72      , 0.74074074, 1.        , 1.        , 1.        ,
        0.7       ],
       [0.88      , 0.66666667, 0.95238095, 0.9       , 0.71428571,
        0.5       ]])

In [11]:
R3

array([[2.85714286e-01, 0.00000000e+00, 6.66666667e-01, 5.90909091e-07,
        5.00000000e-01, 1.00000000e+00],
       [1.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e-07,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 4.16666667e-01, 1.00000000e+00, 7.22222222e-07,
        1.00000000e+00, 4.00000000e-01],
       [5.71428571e-01, 2.50000000e-01, 6.66666667e-01, 6.50000000e-07,
        5.00000000e-01, 0.00000000e+00]])

In [12]:
from scipy.stats import rankdata

a = np.loadtxt("data14_1_2.txt")
a

array([[0.4671, 0.3662, 0.5056, 0.4931, 0.4811, 0.7089],
       [0.5839, 0.6591, 0.455 , 0.401 , 0.2887, 0.3544],
       [0.4204, 0.4882, 0.5308, 0.5853, 0.6736, 0.4962],
       [0.5139, 0.4394, 0.5056, 0.5392, 0.4811, 0.3544]])

In [13]:
bp = a.max(axis=0)
bp

array([0.5839, 0.6591, 0.5308, 0.5853, 0.6736, 0.7089])

In [14]:
bm = a.min(axis=0)
bm

array([0.4204, 0.3662, 0.455 , 0.401 , 0.2887, 0.3544])

In [15]:
d1 = np.linalg.norm(a - bp, axis=1)
d1

array([0.38160815, 0.55993784, 0.31808859, 0.46760543])

In [16]:
d2 = np.linalg.norm(a - bm, axis=1)
d2

array([0.41941825, 0.33544397, 0.47207137, 0.2697737 ])

In [17]:
f1 = d2 / (d1 + d2)
f1

array([0.52360103, 0.37463791, 0.59743773, 0.36585481])

In [18]:
c = bp - a
m1 = c.max()
m2 = c.min()
r = 0.5
xs = (m2 + r * m1) / (c + r * m1)
xs

array([[0.62231205, 0.39651798, 0.88421778, 0.67609345, 0.49993506,
        1.        ],
       [1.        , 1.        , 0.71742777, 0.51081619, 0.33333333,
        0.35186032],
       [0.54066582, 0.5296546 , 1.        , 1.        , 1.        ,
        0.47500926],
       [0.73328253, 0.46694165, 0.88421778, 0.80674911, 0.49993506,
        0.35186032]])

In [19]:
f2 = xs.mean(axis=1)
f2

array([0.67984605, 0.6522396 , 0.75755495, 0.62383107])

In [20]:
n = a.shape[0]
s = a.sum(axis=0)  #逐列求和
P = a / s  #求特征比重矩阵
e = -(P * np.log(P)).sum(axis=0) / np.log(n)  #计算熵值
g = 1 - e
w = g / sum(g)  #计算差异系数和权重系数
f3 = P @ w  #计算各对象的评价值
f3

array([0.27874158, 0.20997757, 0.28653868, 0.22474217])

In [21]:
R = rankdata(a, axis=0)  #逐列编秩
R

array([[2. , 1. , 2.5, 2. , 2.5, 4. ],
       [4. , 4. , 1. , 1. , 1. , 1.5],
       [1. , 3. , 4. , 4. , 4. , 3. ],
       [3. , 2. , 2.5, 3. , 2.5, 1.5]])

In [22]:
RSR = R.mean(axis=1) / n  #计算秩和比
RSR

array([0.58333333, 0.52083333, 0.79166667, 0.60416667])

In [24]:
a = np.array([
    [0.4, 0.3, 0.5, 0.3],
    [0.3, 0.3, 0.4, 0.4],
    [0.2, 0.3, 0.3, 0.3]
])
b = np.array([0.2, 0.3, 0.4, 0.3])
n = a.shape[0]
N = []
for e in a:
    N.append(1 - sum(abs(e - b)) / n)
print("海明贴近度为：", np.round(N, 4))

贴近度为： [0.9    0.9333 0.9667]


In [25]:
N = []
for e in a:
    N.append(1 - np.sqrt(sum((e - b) ** 2)) / np.sqrt(n))
N

[0.8709005551264194, 0.9183503419072274, 0.9422649730810374]

In [31]:
a = np.loadtxt("data14_4.txt")
a

array([[4.7e+03, 6.7e+03, 5.9e+03, 8.8e+03, 7.6e+03],
       [5.0e+03, 5.5e+03, 5.3e+03, 6.8e+03, 6.0e+03],
       [4.0e+00, 6.1e+00, 5.5e+00, 7.0e+00, 6.8e+00],
       [3.0e+01, 5.0e+01, 4.0e+01, 2.0e+02, 1.6e+02],
       [1.5e+03, 7.0e+02, 1.0e+03, 5.0e+01, 1.0e+02]])

In [26]:
f1 = lambda x: x / 8800
f2 = lambda x: 1 - x / 8000
f3 = lambda x: (x <= 5.5) + (8 - x) / (8 - 5.5) * ((x > 5.5) & (x < 8))
f4 = lambda x: 1 - x / 200
f5 = lambda x: (x - 50) / (1500 - 50)

In [28]:
R = []
for i in range(len(a)):
    s = 'f' + str(i + 1) + '(a[' + str(i) + '])'
    R.append(eval(s))
R = np.array(R)
R

array([[0.53409091, 0.76136364, 0.67045455, 1.        , 0.86363636],
       [0.375     , 0.3125    , 0.3375    , 0.15      , 0.25      ],
       [1.        , 0.76      , 1.        , 0.4       , 0.48      ],
       [0.85      , 0.75      , 0.8       , 0.        , 0.2       ],
       [1.        , 0.44827586, 0.65517241, 0.        , 0.03448276]])

In [27]:
w = np.array([0.25, 0.2, 0.2, 0.1, 0.25])
B = w @ R  #计算综合评价值
B

array([0.74352273, 0.59190987, 0.67890674, 0.36      , 0.39052978])

In [35]:
import cvxpy as cp

d = np.loadtxt("data14_5.txt")
a = d[:, :3]
b = d[:, 3:]
u = cp.Variable(3, pos=True)
v = cp.Variable(2, pos=True)
for j in range(10):
    con = [a @ u >= b @ v, a[j] @ u == 1]
    obj = cp.Maximize(b[j] @ v)
    prob = cp.Problem(obj, con)
    prob.solve(solver="GLPK_MI")
    print(prob.value)
    print(u.value)
    print(v.value)
    print("---------------")

0.29018429424239417
[0.         1.53846154 0.        ]
[8.01392693e-05 0.00000000e+00]
---------------
0.28535712948581976
[0.         0.89968161 0.0109388 ]
[7.23705629e-05 0.00000000e+00]
---------------
0.29682609191699816
[0.         0.90294104 0.01097843]
[7.26327528e-05 0.00000000e+00]
---------------
0.34251514458756976
[0.         0.86815421 0.01055547]
[6.98344934e-05 0.00000000e+00]
---------------
0.4594711927591651
[0.         1.31578947 0.        ]
[6.15768731e-05 1.91400785e-01]
---------------
0.7182608695652174
[0.         1.44927536 0.        ]
[0.        1.2173913]
---------------
0.9069108317738916
[0.         1.63934426 0.        ]
[7.67187271e-05 2.38466552e-01]
---------------
0.9999999999999999
[0.         1.0278863  0.01249758]
[8.26833731e-05 0.00000000e+00]
---------------
1.0
[2.63444656e-02 8.32690761e-01 7.80072578e-04]
[7.35114123e-05 0.00000000e+00]
---------------
0.9999999999999999
[0.         0.         0.03436426]
[0. 1.]
---------------
