In [1]:
from sklearn.model_selection import train_test_split
import torch
import torch.nn as nn
import pandas as pd

df = pd.read_excel("data3.xlsx", header=0)
df["Date"] = pd.to_datetime(df["Date"])
df

Unnamed: 0  Unnamed: 1  Unnamed: 2       Date  Contest number   Word  \
0             0         NaN         NaN 2022-01-07             202  slump   
1             1         NaN         NaN 2022-01-08             203  crank   
2             2         NaN         NaN 2022-01-09             204  gorge   
3             3         NaN         NaN 2022-01-10             205  query   
4             4         NaN         NaN 2022-01-11             206  drink   
..          ...         ...         ...        ...             ...    ...   
350         350         NaN         NaN 2022-12-27             556  condo   
351         351         NaN         NaN 2022-12-28             557  impel   
352         352         NaN         NaN 2022-12-29             558  havoc   
353         353         NaN         NaN 2022-12-30             559  molar   
354         354         NaN         NaN 2022-12-31             560  manly   

     Number of  reported results  Number in hard mode  1 try  2 tries  ...  \
0                          80630                 1362      1        3  ...   
1                         101503                 1763      1        5  ...   
2                          91477                 1913      1        3  ...   
3                         107134                 2242      1        4  ...   
4                         153880                 3017      1        9  ...   
..                           ...                  ...    ...      ...  ...   
350                        20879                 2012      0        2  ...   
351                        20160                 1937      0        3  ...   
352                        20001                 1919      0        2  ...   
353                        21204                 1973      0        4  ...   
354                        20380                 1899      0        2  ...   

     5 tries  6 tries  7 or more tries (X)     ratio  vowel  len  uniq  star  \
0         24        9                    1  0.016892      1    5     5     2   
1         24       14                    2  0.017369      1    5     5     2   
2         30       22                    4  0.020912      2    5     4     1   
3         30       17                    2  0.020927      2    5     5     2   
4         16        5                    1  0.019606      1    5     5     4   
..       ...      ...                  ...       ...    ...  ...   ...   ...   
350       29       14                    3  0.096365      2    5     4     1   
351       25        9                    1  0.096081      2    5     5     2   
352       30       12                    2  0.095945      2    5     5     3   
353       26        9                    1  0.093048      2    5     5     2   
354       29       12                    2  0.093180      1    5     5     2   

     three_s  three_ss  
0       0.27        27  
1       0.29        29  
2       0.17        17  
3       0.21        21  
4       0.45        45  
..       ...       ...  
350     0.19        19  
351     0.24        24  
352     0.18        18  
353     0.25        25  
354     0.19        19  

[355 rows x 22 columns]

In [2]:
df = df.drop(df[df["len"] == 4].index.values)
df = df.drop(df[df["len"] == 6].index.values)
len(df)

355

In [3]:
u_m = df["uniq"].mean()
u_s = df["uniq"].std()
df["uniq"] = (df["uniq"] - u_m) / u_s

In [4]:
s_m = df["star"].mean()
s_s = df["star"].std()
df["star"] = (df["star"] - s_m) / s_s

In [5]:
df

Unnamed: 0  Unnamed: 1  Unnamed: 2       Date  Contest number   Word  \
0             0         NaN         NaN 2022-01-07             202  slump   
1             1         NaN         NaN 2022-01-08             203  crank   
2             2         NaN         NaN 2022-01-09             204  gorge   
3             3         NaN         NaN 2022-01-10             205  query   
4             4         NaN         NaN 2022-01-11             206  drink   
..          ...         ...         ...        ...             ...    ...   
350         350         NaN         NaN 2022-12-27             556  condo   
351         351         NaN         NaN 2022-12-28             557  impel   
352         352         NaN         NaN 2022-12-29             558  havoc   
353         353         NaN         NaN 2022-12-30             559  molar   
354         354         NaN         NaN 2022-12-31             560  manly   

     Number of  reported results  Number in hard mode  1 try  2 tries  ...  \
0                          80630                 1362      1        3  ...   
1                         101503                 1763      1        5  ...   
2                          91477                 1913      1        3  ...   
3                         107134                 2242      1        4  ...   
4                         153880                 3017      1        9  ...   
..                           ...                  ...    ...      ...  ...   
350                        20879                 2012      0        2  ...   
351                        20160                 1937      0        3  ...   
352                        20001                 1919      0        2  ...   
353                        21204                 1973      0        4  ...   
354                        20380                 1899      0        2  ...   

     5 tries  6 tries  7 or more tries (X)     ratio  vowel  len      uniq  \
0         24        9                    1  0.016892      1    5  0.604574   
1         24       14                    2  0.017369      1    5  0.604574   
2         30       22                    4  0.020912      2    5 -1.420179   
3         30       17                    2  0.020927      2    5  0.604574   
4         16        5                    1  0.019606      1    5  0.604574   
..       ...      ...                  ...       ...    ...  ...       ...   
350       29       14                    3  0.096365      2    5 -1.420179   
351       25        9                    1  0.096081      2    5  0.604574   
352       30       12                    2  0.095945      2    5  0.604574   
353       26        9                    1  0.093048      2    5  0.604574   
354       29       12                    2  0.093180      1    5  0.604574   

         star  three_s  three_ss  
0   -0.517873     0.27        27  
1   -0.517873     0.29        29  
2   -1.410324     0.17        17  
3   -0.517873     0.21        21  
4    1.267029     0.45        45  
..        ...      ...       ...  
350 -1.410324     0.19        19  
351 -0.517873     0.24        24  
352  0.374578     0.18        18  
353 -0.517873     0.25        25  
354 -0.517873     0.19        19  

[355 rows x 22 columns]

In [6]:
dic = {j: i
       for i, j in enumerate('abcdefghijklmnopqrstuvwxyz', 0)}
dic["ï"] = dic["i"]
dic

{'a': 0,
 'b': 1,
 'c': 2,
 'd': 3,
 'e': 4,
 'f': 5,
 'g': 6,
 'h': 7,
 'i': 8,
 'j': 9,
 'k': 10,
 'l': 11,
 'm': 12,
 'n': 13,
 'o': 14,
 'p': 15,
 'q': 16,
 'r': 17,
 's': 18,
 't': 19,
 'u': 20,
 'v': 21,
 'w': 22,
 'x': 23,
 'y': 24,
 'z': 25,
 'ï': 8}

In [7]:

words_list = []
for i in df["Word"].values:
    words_list.append(([dic[j] for j in i]))
words_list = torch.LongTensor(words_list)
words_list

tensor([[18, 11, 20, 12, 15],
        [ 2, 17,  0, 13, 10],
        [ 6, 14, 17,  6,  4],
        ...,
        [ 7,  0, 21, 14,  2],
        [12, 14, 11,  0, 17],
        [12,  0, 13, 11, 24]])

In [8]:
embedding = nn.Embedding(26, 1)
words_list = embedding(words_list)
words_list = words_list.view(-1, 5)
words_list

tensor([[-0.4826, -1.6837, -0.3317,  0.5637, -0.6392],
        [-0.4025, -1.1929, -0.7567,  0.8559, -0.4253],
        [-1.0653, -0.5986, -1.1929, -1.0653, -0.0307],
        ...,
        [ 0.0538, -0.7567,  0.3571, -0.5986, -0.4025],
        [ 0.5637, -0.5986, -1.6837, -0.7567, -1.1929],
        [ 0.5637, -0.7567,  0.8559, -1.6837, -1.9005]],
       grad_fn=<ViewBackward0>)

In [9]:
max_size = len(words_list)
data = torch.cat((words_list, torch.Tensor(df["uniq"]).unsqueeze(1), torch.Tensor(df["star"]).unsqueeze(1)), dim=1)
# data = torch.cat((words_list, ), dim=1)
data

tensor([[-0.4826, -1.6837, -0.3317,  ..., -0.6392,  0.6046, -0.5179],
        [-0.4025, -1.1929, -0.7567,  ..., -0.4253,  0.6046, -0.5179],
        [-1.0653, -0.5986, -1.1929,  ..., -0.0307, -1.4202, -1.4103],
        ...,
        [ 0.0538, -0.7567,  0.3571,  ..., -0.4025,  0.6046,  0.3746],
        [ 0.5637, -0.5986, -1.6837,  ..., -1.1929,  0.6046, -0.5179],
        [ 0.5637, -0.7567,  0.8559,  ..., -1.9005,  0.6046, -0.5179]],
       grad_fn=<CatBackward0>)

In [10]:
df.iloc[:, 8: 15]

1 try  2 tries  3 tries  4 tries  5 tries  6 tries  7 or more tries (X)
0        1        3       23       39       24        9                    1
1        1        5       23       31       24       14                    2
2        1        3       13       27       30       22                    4
3        1        4       16       30       30       17                    2
4        1        9       35       34       16        5                    1
..     ...      ...      ...      ...      ...      ...                  ...
350      0        2       17       35       29       14                    3
351      0        3       21       40       25        9                    1
352      0        2       16       38       30       12                    2
353      0        4       21       38       26        9                    1
354      0        2       17       37       29       12                    2

[355 rows x 7 columns]

In [11]:
per = df.iloc[:, 8: 15]
per = [([j / 100 for j in i]) for i in per.values]
per = torch.Tensor(per)
per

tensor([[0.0100, 0.0300, 0.2300,  ..., 0.2400, 0.0900, 0.0100],
        [0.0100, 0.0500, 0.2300,  ..., 0.2400, 0.1400, 0.0200],
        [0.0100, 0.0300, 0.1300,  ..., 0.3000, 0.2200, 0.0400],
        ...,
        [0.0000, 0.0200, 0.1600,  ..., 0.3000, 0.1200, 0.0200],
        [0.0000, 0.0400, 0.2100,  ..., 0.2600, 0.0900, 0.0100],
        [0.0000, 0.0200, 0.1700,  ..., 0.2900, 0.1200, 0.0200]])

In [12]:
device = "cuda:0" if torch.cuda.is_available() else "cpu"

In [13]:
data = data.to(device)
per = per.to(device)
data.device

device(type='cuda', index=0)

In [14]:
train_size = int(len(data) * 0.9)
train_size

319

In [15]:
x_train = data[:train_size]
x_test = data[train_size:]
y_train = per[:train_size]
y_test = per[train_size:]
x_train.shape, x_test.shape, y_train.shape, y_test.shape

(torch.Size([319, 7]),
 torch.Size([36, 7]),
 torch.Size([319, 7]),
 torch.Size([36, 7]))

In [16]:
# x_train_w = torch.LongTensor(x_train[:][0:5])
# x_train_w

In [17]:
# x_train_w = torch.LongTensor(x_train)
# x_test_w = torch.LongTensor(x_test)
# y_train_w = torch.Tensor(y_train)
# y_test_w = torch.Tensor(y_test)
# x_test_w.shape

In [18]:
# embedding = nn.Embedding(26, 1)
# x_train = embedding(x_train)
# x_train = x_train.view(-1, 5)
# x_train

In [19]:
# x_test = embedding(x_test)
# x_test = x_test.view(-1, 5)
# x_test

In [20]:
class MLP(nn.Module):
    def __init__(self):
        super(MLP, self).__init__()
        self.net = nn.Sequential(
            nn.Linear(7, 128),
            nn.ReLU(),
            nn.Linear(128, 256),
            nn.ReLU(),
            nn.Linear(256, 7),
            nn.ReLU(),
        )

    def forward(self, x):
        out = self.net(x)
        # out = [[j / sum(i) for j in i] for i in out.tolist()]
        s = torch.sum(out, axis=1)
        s.unsqueeze_(0)
        s = s.repeat_interleave(7, axis=1).view(-1, 7)
        return torch.div(out, s)

In [21]:
model = MLP().to(device)
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [22]:
x_train.device

device(type='cuda', index=0)

In [23]:
def train(num_epochs):
    for epoch in range(num_epochs):
        pred = model(x_train)
        # print(pred.tolist())
        # print(pp)
        # print(pred)
        loss = criterion(pred, y_train)
        optimizer.zero_grad()
        loss.backward(retain_graph=True)
        optimizer.step()
        train_l_sum = loss.item()
        if epoch % 1000 == 0:
            print(
                'epoch %d, loss %.4f'
                % (epoch + 1, train_l_sum))
    # px.line(y=np.array(y_train.cpu().detach_())[:, 0]).show()


def test():
    with torch.no_grad():
        pred = model(x_test)
        loss = criterion(pred, y_test)
        print(loss)
        print(pred[0])
        print(y_test[0])

In [24]:
train(2000)

epoch 1, loss 0.0846
epoch 1001, loss 0.0000


In [25]:
test()

tensor(0.0049, device='cuda:0')
tensor([0.0000, 0.0075, 0.1851, 0.3391, 0.3025, 0.1471, 0.0187],
       device='cuda:0')
tensor([0.0500, 0.1300, 0.2500, 0.2700, 0.1900, 0.1000, 0.0200],
       device='cuda:0')


In [26]:
w = "eerie"
w = [dic[i] for i in w]
[w]

[[4, 4, 17, 8, 4]]

In [27]:
w = embedding(torch.LongTensor([[4, 4, 17, 8, 4]])).view(-1, 5)
w = torch.cat((w, torch.Tensor([(3 - u_m) / u_s]).unsqueeze(1), torch.Tensor([(2 - s_m) / s_s]).unsqueeze(1)), dim=1)
w = w.to(device)
w

tensor([[-0.0307, -0.0307, -1.1929,  0.0333, -0.0307, -3.4449, -0.5179]],
       device='cuda:0', grad_fn=<ToCopyBackward0>)

In [28]:
model(w)

tensor([[0.0000, 0.0039, 0.1387, 0.3404, 0.3366, 0.1805, 0.0000]],
       device='cuda:0', grad_fn=<DivBackward0>)

In [28]:
# tash  1
# rprobe
# clen
