In [15]:
from sklearn.model_selection import train_test_split
import torch
import torch.nn as nn
import pandas as pd

df = pd.read_excel("data.xlsx", header=1)
# df["Date"] = pd.to_datetime(df["Date"])
df

Date  Contest number   Word  Number of  reported results  \
0   2022-01-07             202  slump                        80630   
1   2022-01-08             203  crank                       101503   
2   2022-01-09             204  gorge                        91477   
3   2022-01-10             205  query                       107134   
4   2022-01-11             206  drink                       153880   
..         ...             ...    ...                          ...   
354 2022-12-27             556  condo                        20879   
355 2022-12-28             557  impel                        20160   
356 2022-12-29             558  havoc                        20001   
357 2022-12-30             559  molar                        21204   
358 2022-12-31             560  manly                        20380   

     Number in hard mode  1 try  2 tries  3 tries  4 tries  5 tries  6 tries  \
0                   1362      1        3       23       39       24        9   
1                   1763      1        5       23       31       24       14   
2                   1913      1        3       13       27       30       22   
3                   2242      1        4       16       30       30       17   
4                   3017      1        9       35       34       16        5   
..                   ...    ...      ...      ...      ...      ...      ...   
354                 2012      0        2       17       35       29       14   
355                 1937      0        3       21       40       25        9   
356                 1919      0        2       16       38       30       12   
357                 1973      0        4       21       38       26        9   
358                 1899      0        2       17       37       29       12   

     7 or more tries (X)     ratio  
0                      1  0.016892  
1                      2  0.017369  
2                      4  0.020912  
3                      2  0.020927  
4                      1  0.019606  
..                   ...       ...  
354                    3  0.096365  
355                    1  0.096081  
356                    2  0.095945  
357                    1  0.093048  
358                    2  0.093180  

[359 rows x 13 columns]

In [16]:
df["len"] = 0
len(df)

359

In [17]:
max_size = len(df)
for i in range(0, max_size):
    df["len"][i] = len(df["Word"][i])
df

X:\Temp\ipykernel_26524\2739324610.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["len"][i] = len(df["Word"][i])


Date  Contest number   Word  Number of  reported results  \
0   2022-01-07             202  slump                        80630   
1   2022-01-08             203  crank                       101503   
2   2022-01-09             204  gorge                        91477   
3   2022-01-10             205  query                       107134   
4   2022-01-11             206  drink                       153880   
..         ...             ...    ...                          ...   
354 2022-12-27             556  condo                        20879   
355 2022-12-28             557  impel                        20160   
356 2022-12-29             558  havoc                        20001   
357 2022-12-30             559  molar                        21204   
358 2022-12-31             560  manly                        20380   

     Number in hard mode  1 try  2 tries  3 tries  4 tries  5 tries  6 tries  \
0                   1362      1        3       23       39       24        9   
1                   1763      1        5       23       31       24       14   
2                   1913      1        3       13       27       30       22   
3                   2242      1        4       16       30       30       17   
4                   3017      1        9       35       34       16        5   
..                   ...    ...      ...      ...      ...      ...      ...   
354                 2012      0        2       17       35       29       14   
355                 1937      0        3       21       40       25        9   
356                 1919      0        2       16       38       30       12   
357                 1973      0        4       21       38       26        9   
358                 1899      0        2       17       37       29       12   

     7 or more tries (X)     ratio  len  
0                      1  0.016892    5  
1                      2  0.017369    5  
2                      4  0.020912    5  
3                      2  0.020927    5  
4                      1  0.019606    5  
..                   ...       ...  ...  
354                    3  0.096365    5  
355                    1  0.096081    5  
356                    2  0.095945    5  
357                    1  0.093048    5  
358                    2  0.093180    5  

[359 rows x 14 columns]

In [18]:
df[df["len"] == 4].index.values

array([112, 323], dtype=int64)

In [19]:
df[df["len"] == 6].index.values

array([  5, 343], dtype=int64)

In [237]:
df = df.drop(df[df["len"] == 4].index.values)
df = df.drop(df[df["len"] == 6].index.values)
len(df)

355

In [238]:
u_m = df["uniq"].mean()
u_s = df["uniq"].std()
df["uniq"] = (df["uniq"] - u_m) / u_s

In [239]:
s_m = df["star"].mean()
s_s = df["star"].std()
df["star"] = (df["star"] - s_m) / s_s

In [240]:
df

Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1       Date  Contest number  \
0             0             0               0 2022-01-07             202   
1             1             1               1 2022-01-08             203   
2             2             2               2 2022-01-09             204   
3             3             3               3 2022-01-10             205   
4             4             4               4 2022-01-11             206   
..          ...           ...             ...        ...             ...   
350         350           350             350 2022-12-27             556   
351         351           351             351 2022-12-28             557   
352         352           352             352 2022-12-29             558   
353         353           353             353 2022-12-30             559   
354         354           354             354 2022-12-31             560   

      Word  Number of  reported results  Number in hard mode  1 try  2 tries  \
0    slump                        80630                 1362      1        3   
1    crank                       101503                 1763      1        5   
2    gorge                        91477                 1913      1        3   
3    query                       107134                 2242      1        4   
4    drink                       153880                 3017      1        9   
..     ...                          ...                  ...    ...      ...   
350  condo                        20879                 2012      0        2   
351  impel                        20160                 1937      0        3   
352  havoc                        20001                 1919      0        2   
353  molar                        21204                 1973      0        4   
354  manly                        20380                 1899      0        2   

     ...  5 tries  6 tries  7 or more tries (X)     ratio  vowel  len  \
0    ...       24        9                    1  0.016892      1    5   
1    ...       24       14                    2  0.017369      1    5   
2    ...       30       22                    4  0.020912      2    5   
3    ...       30       17                    2  0.020927      2    5   
4    ...       16        5                    1  0.019606      1    5   
..   ...      ...      ...                  ...       ...    ...  ...   
350  ...       29       14                    3  0.096365      2    5   
351  ...       25        9                    1  0.096081      2    5   
352  ...       30       12                    2  0.095945      2    5   
353  ...       26        9                    1  0.093048      2    5   
354  ...       29       12                    2  0.093180      1    5   

         uniq      star  Unnamed: 20  Unnamed: 21  
0    0.604574 -0.517873          NaN          NaN  
1    0.604574 -0.517873          NaN          NaN  
2   -1.420179 -1.410324          NaN          NaN  
3    0.604574 -0.517873          NaN          NaN  
4    0.604574  1.267029          NaN          NaN  
..        ...       ...          ...          ...  
350 -1.420179 -1.410324          NaN          NaN  
351  0.604574 -0.517873          NaN          NaN  
352  0.604574  0.374578          NaN          NaN  
353  0.604574 -0.517873          NaN          NaN  
354  0.604574 -0.517873          NaN          NaN  

[355 rows x 22 columns]

In [241]:
dic = {j: i
       for i, j in enumerate('abcdefghijklmnopqrstuvwxyz', 0)}
dic["ï"] = dic["i"]
dic

{'a': 0,
 'b': 1,
 'c': 2,
 'd': 3,
 'e': 4,
 'f': 5,
 'g': 6,
 'h': 7,
 'i': 8,
 'j': 9,
 'k': 10,
 'l': 11,
 'm': 12,
 'n': 13,
 'o': 14,
 'p': 15,
 'q': 16,
 'r': 17,
 's': 18,
 't': 19,
 'u': 20,
 'v': 21,
 'w': 22,
 'x': 23,
 'y': 24,
 'z': 25,
 'ï': 8}

In [242]:

words_list = []
for i in df["Word"].values:
    words_list.append(([dic[j] for j in i]))
words_list = torch.LongTensor(words_list)
words_list

tensor([[18, 11, 20, 12, 15],
        [ 2, 17,  0, 13, 10],
        [ 6, 14, 17,  6,  4],
        ...,
        [ 7,  0, 21, 14,  2],
        [12, 14, 11,  0, 17],
        [12,  0, 13, 11, 24]])

In [243]:
embedding = nn.Embedding(26, 1)
words_list = embedding(words_list)
words_list = words_list.view(-1, 5)
words_list

tensor([[ 1.2918, -0.5160,  0.6721,  0.2530, -0.0955],
        [-1.4895,  0.4472,  0.0509,  0.2151,  0.8530],
        [ 0.4216,  0.4401,  0.4472,  0.4216,  0.8431],
        ...,
        [-0.2113,  0.0509,  0.3175,  0.4401, -1.4895],
        [ 0.2530,  0.4401, -0.5160,  0.0509,  0.4472],
        [ 0.2530,  0.0509,  0.2151, -0.5160,  1.5313]],
       grad_fn=<ViewBackward0>)

In [244]:
max_size = len(words_list)
data = torch.cat((words_list, torch.Tensor(df["uniq"]).unsqueeze(1), torch.Tensor(df["star"]).unsqueeze(1)), dim=1)
# data = torch.cat((words_list, ), dim=1)
data

tensor([[ 1.2918, -0.5160,  0.6721,  ..., -0.0955,  0.6046, -0.5179],
        [-1.4895,  0.4472,  0.0509,  ...,  0.8530,  0.6046, -0.5179],
        [ 0.4216,  0.4401,  0.4472,  ...,  0.8431, -1.4202, -1.4103],
        ...,
        [-0.2113,  0.0509,  0.3175,  ..., -1.4895,  0.6046,  0.3746],
        [ 0.2530,  0.4401, -0.5160,  ...,  0.4472,  0.6046, -0.5179],
        [ 0.2530,  0.0509,  0.2151,  ...,  1.5313,  0.6046, -0.5179]],
       grad_fn=<CatBackward0>)

In [245]:
df.iloc[:, 8: 15]

1 try  2 tries  3 tries  4 tries  5 tries  6 tries  7 or more tries (X)
0        1        3       23       39       24        9                    1
1        1        5       23       31       24       14                    2
2        1        3       13       27       30       22                    4
3        1        4       16       30       30       17                    2
4        1        9       35       34       16        5                    1
..     ...      ...      ...      ...      ...      ...                  ...
350      0        2       17       35       29       14                    3
351      0        3       21       40       25        9                    1
352      0        2       16       38       30       12                    2
353      0        4       21       38       26        9                    1
354      0        2       17       37       29       12                    2

[355 rows x 7 columns]

In [246]:
per = df.iloc[:, 8: 15]
per = [([j / 100 for j in i]) for i in per.values]
per = torch.Tensor(per)
per

tensor([[0.0100, 0.0300, 0.2300,  ..., 0.2400, 0.0900, 0.0100],
        [0.0100, 0.0500, 0.2300,  ..., 0.2400, 0.1400, 0.0200],
        [0.0100, 0.0300, 0.1300,  ..., 0.3000, 0.2200, 0.0400],
        ...,
        [0.0000, 0.0200, 0.1600,  ..., 0.3000, 0.1200, 0.0200],
        [0.0000, 0.0400, 0.2100,  ..., 0.2600, 0.0900, 0.0100],
        [0.0000, 0.0200, 0.1700,  ..., 0.2900, 0.1200, 0.0200]])

In [247]:
device = "cuda:0" if torch.cuda.is_available() else "cpu"

In [248]:
data = data.to(device)
per = per.to(device)
data.device

device(type='cuda', index=0)

In [249]:
train_size = int(len(data) * 0.9)
train_size

319

In [250]:
x_train = data[:train_size]
x_test = data[train_size:]
y_train = per[:train_size]
y_test = per[train_size:]
x_train.shape, x_test.shape, y_train.shape, y_test.shape

(torch.Size([319, 7]),
 torch.Size([36, 7]),
 torch.Size([319, 7]),
 torch.Size([36, 7]))

In [251]:
# x_train_w = torch.LongTensor(x_train[:][0:5])
# x_train_w

In [252]:
# x_train_w = torch.LongTensor(x_train)
# x_test_w = torch.LongTensor(x_test)
# y_train_w = torch.Tensor(y_train)
# y_test_w = torch.Tensor(y_test)
# x_test_w.shape

In [253]:
# embedding = nn.Embedding(26, 1)
# x_train = embedding(x_train)
# x_train = x_train.view(-1, 5)
# x_train

In [254]:
# x_test = embedding(x_test)
# x_test = x_test.view(-1, 5)
# x_test

In [255]:
class MLP(nn.Module):
    def __init__(self):
        super(MLP, self).__init__()
        self.net = nn.Sequential(
            nn.Linear(7, 30),
            nn.ReLU(),
            nn.Linear(30, 7),
            nn.ReLU()
        )

    def forward(self, x):
        out = self.net(x)
        # out = [[j / sum(i) for j in i] for i in out.tolist()]
        s = torch.sum(out, axis=1)
        s.unsqueeze_(0)
        s = s.repeat_interleave(7, axis=1).view(-1, 7)
        return torch.div(out, s)

In [256]:
model = MLP().to(device)
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

In [257]:
x_train.device

device(type='cuda', index=0)

In [258]:
def train(num_epochs):
    for epoch in range(num_epochs):
        pred = model(x_train)
        # print(pred.tolist())
        # print(pp)
        # print(pred)
        loss = criterion(pred, y_train)
        optimizer.zero_grad()
        loss.backward(retain_graph=True)
        optimizer.step()
        train_l_sum = loss.item()
        print(
            'epoch %d, loss %.4f'
            % (epoch + 1, train_l_sum))
    # px.line(y=np.array(y_train.cpu().detach_())[:, 0]).show()


def test():
    with torch.no_grad():
        pred = model(x_test)
        loss = criterion(pred, y_test)
        print(loss)
        print(pred[0])
        print(y_test[0])

In [259]:
train(500000)

epoch 1, loss 0.0554
epoch 2, loss 0.0531
epoch 3, loss 0.0509
epoch 4, loss 0.0488
epoch 5, loss 0.0468
epoch 6, loss 0.0449
epoch 7, loss 0.0431
epoch 8, loss 0.0414
epoch 9, loss 0.0398
epoch 10, loss 0.0383
epoch 11, loss 0.0369
epoch 12, loss 0.0356
epoch 13, loss 0.0344
epoch 14, loss 0.0333
epoch 15, loss 0.0323
epoch 16, loss 0.0313
epoch 17, loss 0.0304
epoch 18, loss 0.0296
epoch 19, loss 0.0288
epoch 20, loss 0.0280
epoch 21, loss 0.0272
epoch 22, loss 0.0265
epoch 23, loss 0.0258
epoch 24, loss 0.0251
epoch 25, loss 0.0244
epoch 26, loss 0.0237
epoch 27, loss 0.0230
epoch 28, loss 0.0224
epoch 29, loss 0.0218
epoch 30, loss 0.0212
epoch 31, loss 0.0206
epoch 32, loss 0.0200
epoch 33, loss 0.0194
epoch 34, loss 0.0189
epoch 35, loss 0.0183
epoch 36, loss 0.0177
epoch 37, loss 0.0171
epoch 38, loss 0.0166
epoch 39, loss 0.0160
epoch 40, loss 0.0154
epoch 41, loss 0.0149
epoch 42, loss 0.0143
epoch 43, loss 0.0137
epoch 44, loss 0.0131
epoch 45, loss 0.0126
epoch 46, loss 0.01

KeyboardInterrupt: 

In [ ]:
test()

In [ ]:
w = "eerie"
w = [dic[i] for i in w]
[w]

torch.Size([1])

In [264]:
w = embedding(torch.LongTensor([[4, 4, 17, 8, 4]])).view(-1, 5)
w = torch.cat((w, torch.Tensor([(3 - u_m) / u_s]).unsqueeze(1), torch.Tensor([(2 - s_m) / s_s]).unsqueeze(1)), dim=1)
w = w.to(device)
w

tensor([[ 0.8431,  0.8431,  0.4472, -0.9689,  0.8431, -3.4449, -0.5179]],
       device='cuda:0', grad_fn=<ToCopyBackward0>)

In [ ]:
model(w)