In [28]:
import numpy as np
import sympy as sp

A = np.array([[3, 1, 1, 1, 1, -1],
              [1, 3, 1, 1, -1, 1],
              [1, -1, 3, 1, 1, 1],
              [-1, 1, 1, 3, 1, 1],
              [1, 1, -1, 1, 3, 1],
              [1, 1, 1, -1, 1, 3]],
             dtype=int)
A

array([[ 3,  1,  1,  1,  1, -1],
       [ 1,  3,  1,  1, -1,  1],
       [ 1, -1,  3,  1,  1,  1],
       [-1,  1,  1,  3,  1,  1],
       [ 1,  1, -1,  1,  3,  1],
       [ 1,  1,  1, -1,  1,  3]])

In [29]:
Az1 = np.hstack([A.T, -np.ones((6, 1))])
Az1

array([[ 3.,  1.,  1., -1.,  1.,  1., -1.],
       [ 1.,  3., -1.,  1.,  1.,  1., -1.],
       [ 1.,  1.,  3.,  1., -1.,  1., -1.],
       [ 1.,  1.,  1.,  3.,  1., -1., -1.],
       [ 1., -1.,  1.,  1.,  3.,  1., -1.],
       [-1.,  1.,  1.,  1.,  1.,  3., -1.]])

In [30]:
Az2 = np.vstack([Az1, [1, 1, 1, 1, 1, 1, 0]])  #构造完整的系数阵
Az2

array([[ 3.,  1.,  1., -1.,  1.,  1., -1.],
       [ 1.,  3., -1.,  1.,  1.,  1., -1.],
       [ 1.,  1.,  3.,  1., -1.,  1., -1.],
       [ 1.,  1.,  1.,  3.,  1., -1., -1.],
       [ 1., -1.,  1.,  1.,  3.,  1., -1.],
       [-1.,  1.,  1.,  1.,  1.,  3., -1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  0.]])

In [31]:
B = np.array([[0, 0, 0, 0, 0, 0, 1]]).T  #非线性方程组的常数项列
B

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1]])

In [32]:
Az3 = np.hstack([Az2, B])  #构造增广阵
Az3

array([[ 3.,  1.,  1., -1.,  1.,  1., -1.,  0.],
       [ 1.,  3., -1.,  1.,  1.,  1., -1.,  0.],
       [ 1.,  1.,  3.,  1., -1.,  1., -1.,  0.],
       [ 1.,  1.,  1.,  3.,  1., -1., -1.,  0.],
       [ 1., -1.,  1.,  1.,  3.,  1., -1.,  0.],
       [-1.,  1.,  1.,  1.,  1.,  3., -1.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.]])

In [33]:
Az4 = sp.Matrix(Az3.astype(int))  #转换为符号矩阵
Az4

Matrix([
[ 3,  1,  1, -1,  1,  1, -1, 0],
[ 1,  3, -1,  1,  1,  1, -1, 0],
[ 1,  1,  3,  1, -1,  1, -1, 0],
[ 1,  1,  1,  3,  1, -1, -1, 0],
[ 1, -1,  1,  1,  3,  1, -1, 0],
[-1,  1,  1,  1,  1,  3, -1, 0],
[ 1,  1,  1,  1,  1,  1,  0, 1]])

In [34]:
s1 = Az4.rref()  #把增广阵化成行最简形
s1

(Matrix([
 [1, 0, 0, 0, 0, -1, 0,   0],
 [0, 1, 0, 0, 0,  1, 0, 1/3],
 [0, 0, 1, 0, 0,  1, 0, 1/3],
 [0, 0, 0, 1, 0, -1, 0,   0],
 [0, 0, 0, 0, 1,  1, 0, 1/3],
 [0, 0, 0, 0, 0,  0, 1,   1],
 [0, 0, 0, 0, 0,  0, 0,   0]]),
 (0, 1, 2, 3, 4, 6))

In [35]:
s2 = np.linalg.pinv(Az2) @ B  #求最小范数解
s2

array([[0.16666667],
       [0.16666667],
       [0.16666667],
       [0.16666667],
       [0.16666667],
       [0.16666667],
       [1.        ]])

In [36]:
print('行最简形为：\n', s1[0]);
print('最小范数解为：\n', s2)
np.savetxt('data15_3.txt', A, fmt='%.0f')

行最简形为：
 Matrix([[1, 0, 0, 0, 0, -1, 0, 0], [0, 1, 0, 0, 0, 1, 0, 1/3], [0, 0, 1, 0, 0, 1, 0, 1/3], [0, 0, 0, 1, 0, -1, 0, 0], [0, 0, 0, 0, 1, 1, 0, 1/3], [0, 0, 0, 0, 0, 0, 1, 1], [0, 0, 0, 0, 0, 0, 0, 0]])
最小范数解为：
 [[0.16666667]
 [0.16666667]
 [0.16666667]
 [0.16666667]
 [0.16666667]
 [0.16666667]
 [1.        ]]


In [37]:
import cvxpy as cp

A = np.loadtxt("data16_3.txt")
A.shape

(6, 6)

In [38]:
x = cp.Variable(6, pos=True)
y = cp.Variable(6, pos=True)
u = cp.Variable()
v = cp.Variable()

In [39]:
ob1 = cp.Maximize(u)
con1 = [A.T @ x >= u, sum(x) == 1]
prob1 = cp.Problem(ob1, con1)
prob1.solve(solver="GLPK_MI")
prob1.value

1.0

In [40]:
x.value

array([0.33333333, 0.        , 0.        , 0.33333333, 0.        ,
       0.33333333])

In [41]:
ob2 = cp.Minimize(v)
con2 = [A @ y <= v, sum(y) == 1]
prob2 = cp.Problem(ob2, con2)
prob2.solve(solver="GLPK_MI")
prob2.value

1.0

In [42]:
y.value

array([0.33333333, 0.        , 0.        , 0.33333333, 0.        ,
       0.33333333])

In [43]:
A = np.array([
    [1 / 3, 1 / 2, -1 / 3],
    [-2 / 5, 1 / 5, -1 / 2],
    [1 / 2, -3 / 5, 1 / 3]
])

x = cp.Variable(3, pos=True)
y = cp.Variable(3, pos=True)
u = cp.Variable()
v = cp.Variable()

In [44]:
ob1 = cp.Maximize(u)
con1 = [A.T @ x >= u, sum(x) == 1]
prob1 = cp.Problem(ob1, con1)
prob1.solve(solver="GLPK_MI")
prob1.value  # u

-0.018867924528301883

In [45]:
x.value

array([0.52830189, 0.        , 0.47169811])

In [46]:
ob2 = cp.Minimize(v)
con2 = [A @ y <= v, sum(y) == 1]
prob2 = cp.Problem(ob2, con2)
prob2.solve(solver="GLPK_MI")
prob2.value

-0.018867924528301938

In [47]:
y.value

array([0.        , 0.37735849, 0.62264151])

In [58]:
from scipy.optimize import minimize

a = np.array([
    [14, 13, 12],
    [13, 12, 12],
    [12, 12, 13]
])
b = np.array([
    [13, 14, 15],
    [14, 15, 15],
    [15, 15, 14]
])
obj = lambda z: sum(z)
con1 = {
    'type': 'ineq',
    'fun': lambda z: z[:3] @ a @ z[3:] - a @ z[3:]
}
con2 = {
    'type': 'ineq',
    'fun': lambda z: z[:3] @ b @ z[3:] - b @ z[:3]
}
con3 = {
    'type': 'eq',
    'fun': lambda z: sum(z[:3]) - 1
}
con4 = {
    'type': 'eq',
    'fun': lambda z: sum(z[3:]) - 1
}
con = [con1, con2, con3, con4]
bd = [(0, 1) for i in range(6)]
s = minimize(obj, np.ones(6), constraints=con, bounds=bd)
s

     fun: 2.000000000015837
     jac: array([1., 1., 1., 1., 1., 1.])
 message: 'Optimization terminated successfully'
    nfev: 49
     nit: 7
    njev: 7
  status: 0
 success: True
       x: array([5.00000000e-01, 2.76541360e-14, 5.00000000e-01, 3.81793969e-11,
       5.00000000e-01, 5.00000000e-01])

In [59]:
x = s.x[:3]
x

array([5.0000000e-01, 2.7654136e-14, 5.0000000e-01])

In [60]:
y = s.x[3:]
y

array([3.81793969e-11, 5.00000000e-01, 5.00000000e-01])

In [61]:
x @ a @ y

12.500000000217035

In [62]:
x @ b @ y

14.500000000210559