In [188]:
import plotly.graph_objs as go
import plotly.express as px
import plotly.io as pio
import numpy as np
import pandas as pd

In [189]:
pio.templates.default = "plotly_white"

In [190]:
from sklearn.decomposition import PCA
from scipy.stats import zscore

In [191]:
a = np.loadtxt("data12_1.txt")
a

array([[2297.86,  589.62,  474.74,  164.19,  290.91,  626.21,  295.2 ,
         199.03],
       [2262.19,  571.69,  461.25,  185.9 ,  337.83,  604.78,  354.66,
         198.96],
       [2303.29,  589.99,  516.21,  236.55,  403.92,  730.05,  438.41,
         225.8 ],
       [2308.7 ,  551.14,  476.45,  293.23,  406.44,  785.74,  494.04,
         254.1 ],
       [2337.65,  589.28,  509.82,  334.05,  442.5 ,  850.15,  563.72,
         246.51],
       [2418.96,  618.6 ,  454.2 ,  429.6 ,  615.  , 1065.12,  594.48,
         164.28],
       [2702.34,  735.01,  475.36,  459.69,  790.26, 1025.99,  741.6 ,
         187.81],
       [3015.32,  779.68,  474.15,  537.95,  865.45, 1200.52,  903.22,
         196.77],
       [3135.65,  849.53,  583.5 ,  629.32,  929.92, 1391.11,  882.41,
         221.85],
       [3415.92, 1038.98,  615.74,  705.72,  976.02, 1449.49,  954.56,
         242.26]])

In [192]:
b = zscore(a, ddof=1)
b

array([[-0.76076777, -0.64214522, -0.54059347, -1.25096611, -1.19811321,
        -1.14171193, -1.38154326, -0.507142  ],
       [-0.84506173, -0.75532164, -0.78862442, -1.13462085, -1.01960322,
        -1.21228148, -1.13035357, -0.50955582],
       [-0.7479358 , -0.63980973,  0.22188565, -0.8631843 , -0.76815981,
        -0.79976409, -0.77655041,  0.41596886],
       [-0.7351511 , -0.88503583, -0.50915293, -0.5594326 , -0.75857232,
        -0.61637547, -0.54154062,  1.39183877],
       [-0.66673758, -0.64429134,  0.10439731, -0.34067564, -0.62137986,
        -0.40427165, -0.24717639,  1.13011253],
       [-0.47458894, -0.4592198 , -0.91824771,  0.17138284,  0.03490684,
         0.30363019, -0.1172303 , -1.70542749],
       [ 0.19508369,  0.2755748 , -0.52919398,  0.33263705,  0.70169414,
         0.17477407,  0.5042804 , -0.89404166],
       [ 0.93470589,  0.55753748, -0.55144138,  0.75203733,  0.98775905,
         0.74950593,  1.18704657, -0.58507366],
       [ 1.21906508,  0.99843949

In [193]:
df = pd.DataFrame(a)
df

0        1       2       3       4        5       6       7
0  2297.86   589.62  474.74  164.19  290.91   626.21  295.20  199.03
1  2262.19   571.69  461.25  185.90  337.83   604.78  354.66  198.96
2  2303.29   589.99  516.21  236.55  403.92   730.05  438.41  225.80
3  2308.70   551.14  476.45  293.23  406.44   785.74  494.04  254.10
4  2337.65   589.28  509.82  334.05  442.50   850.15  563.72  246.51
5  2418.96   618.60  454.20  429.60  615.00  1065.12  594.48  164.28
6  2702.34   735.01  475.36  459.69  790.26  1025.99  741.60  187.81
7  3015.32   779.68  474.15  537.95  865.45  1200.52  903.22  196.77
8  3135.65   849.53  583.50  629.32  929.92  1391.11  882.41  221.85
9  3415.92  1038.98  615.74  705.72  976.02  1449.49  954.56  242.26

In [194]:
md = PCA().fit(b)
md

PCA()

In [195]:
md.explained_variance_

array([6.27943341e+00, 1.30599080e+00, 2.74277611e-01, 9.97624700e-02,
       2.31016993e-02, 1.22233669e-02, 4.69357480e-03, 5.17066158e-04])

In [196]:
md.explained_variance_ratio_

array([7.84929176e-01, 1.63248850e-01, 3.42847014e-02, 1.24703088e-02,
       2.88771241e-03, 1.52792086e-03, 5.86696851e-04, 6.46332697e-05])

In [197]:
xs1 = md.components_
xs1

array([[ 0.39186166,  0.38439344,  0.3059243 ,  0.39231584,  0.38537825,
         0.38961322,  0.38389911,  0.05908768],
       [ 0.0210478 , -0.02214509, -0.47783697,  0.08905605,  0.19878256,
         0.1043221 ,  0.11376475, -0.83634169],
       [-0.14762176, -0.39254883, -0.57745685,  0.20021017,  0.15914777,
         0.1347164 ,  0.4303164 ,  0.47108809],
       [-0.47832186, -0.48941314,  0.44488132,  0.27708115, -0.02393188,
         0.46564673, -0.07989617, -0.18222681],
       [-0.09762149, -0.27604773,  0.34873203, -0.35508891,  0.52307577,
        -0.45643408,  0.4158212 , -0.10824944],
       [-0.70552867,  0.53549607, -0.049896  ,  0.32914209,  0.14716623,
        -0.28505603,  0.02367193,  0.03426265],
       [-0.08102349,  0.10492282,  0.11905975, -0.07206231, -0.68369188,
        -0.02060535,  0.68706375, -0.15212634],
       [ 0.28557308, -0.29011082,  0.09180137,  0.6940343 , -0.15286467,
        -0.55886444, -0.05098258, -0.07665729]])

In [198]:
check = xs1.sum(axis=1, keepdims=True)
check

array([[ 2.69247348],
       [-0.80935049],
       [ 0.2778514 ],
       [-0.06618066],
       [-0.00581264],
       [ 0.02925828],
       [-0.09846306],
       [-0.05807107]])

In [199]:
xs2 = xs1 * np.sign(check)
xs2

array([[ 0.39186166,  0.38439344,  0.3059243 ,  0.39231584,  0.38537825,
         0.38961322,  0.38389911,  0.05908768],
       [-0.0210478 ,  0.02214509,  0.47783697, -0.08905605, -0.19878256,
        -0.1043221 , -0.11376475,  0.83634169],
       [-0.14762176, -0.39254883, -0.57745685,  0.20021017,  0.15914777,
         0.1347164 ,  0.4303164 ,  0.47108809],
       [ 0.47832186,  0.48941314, -0.44488132, -0.27708115,  0.02393188,
        -0.46564673,  0.07989617,  0.18222681],
       [ 0.09762149,  0.27604773, -0.34873203,  0.35508891, -0.52307577,
         0.45643408, -0.4158212 ,  0.10824944],
       [-0.70552867,  0.53549607, -0.049896  ,  0.32914209,  0.14716623,
        -0.28505603,  0.02367193,  0.03426265],
       [ 0.08102349, -0.10492282, -0.11905975,  0.07206231,  0.68369188,
         0.02060535, -0.68706375,  0.15212634],
       [-0.28557308,  0.29011082, -0.09180137, -0.6940343 ,  0.15286467,
         0.55886444,  0.05098258,  0.07665729]])

In [200]:
import statsmodels.api as sm

a = np.loadtxt("data12_2.txt")
a.shape

(13, 5)

In [201]:
mu = a.mean(axis=0)
mu

array([ 7.46153846, 48.15384615, 11.76923077, 30.        , 95.42307692])

In [202]:
s = a.std(axis=0, ddof=1)
s

array([ 5.88239442, 15.56088126,  6.40512615, 16.73817991, 15.0437226 ])

In [203]:
b = (a - mu) / s
b

array([[-0.07846099, -1.4236884 , -0.90072087,  1.79230957, -1.12492615],
       [-1.09845379, -1.23089726,  0.50440368,  1.31436035, -1.40411237],
       [ 0.60153422,  0.50422298, -0.58847097, -0.59743652,  0.5900749 ],
       [ 0.60153422, -1.10236984, -0.58847097,  1.01564209, -0.52002268],
       [-0.07846099,  0.24716813, -0.90072087,  0.17923096,  0.03170246],
       [ 0.60153422,  0.43995926, -0.43234602, -0.47794922,  0.91579215],
       [-0.75845619,  1.46817866,  0.81665358, -1.43384765,  0.48371824],
       [-1.09845379, -1.10236984,  1.59727833,  0.83641113, -1.5237636 ],
       [-0.92845499,  0.37569555,  0.97277853, -0.47794922, -0.15442168],
       [ 2.30152223, -0.07415044, -1.21297077, -0.23897461,  1.36116064],
       [-1.09845379, -0.52399643,  1.75340328,  0.23897461, -0.77261973],
       [ 0.60153422,  1.1468601 , -0.43234602, -1.07538574,  1.18833108],
       [ 0.43153542,  1.27538753, -0.58847097, -1.07538574,  0.92908673]])

In [204]:
zscore(a, ddof=1)

array([[-0.07846099, -1.4236884 , -0.90072087,  1.79230957, -1.12492615],
       [-1.09845379, -1.23089726,  0.50440368,  1.31436035, -1.40411237],
       [ 0.60153422,  0.50422298, -0.58847097, -0.59743652,  0.5900749 ],
       [ 0.60153422, -1.10236984, -0.58847097,  1.01564209, -0.52002268],
       [-0.07846099,  0.24716813, -0.90072087,  0.17923096,  0.03170246],
       [ 0.60153422,  0.43995926, -0.43234602, -0.47794922,  0.91579215],
       [-0.75845619,  1.46817866,  0.81665358, -1.43384765,  0.48371824],
       [-1.09845379, -1.10236984,  1.59727833,  0.83641113, -1.5237636 ],
       [-0.92845499,  0.37569555,  0.97277853, -0.47794922, -0.15442168],
       [ 2.30152223, -0.07415044, -1.21297077, -0.23897461,  1.36116064],
       [-1.09845379, -0.52399643,  1.75340328,  0.23897461, -0.77261973],
       [ 0.60153422,  1.1468601 , -0.43234602, -1.07538574,  1.18833108],
       [ 0.43153542,  1.27538753, -0.58847097, -1.07538574,  0.92908673]])

In [205]:
b[:, : -1].T

array([[-0.07846099, -1.09845379,  0.60153422,  0.60153422, -0.07846099,
         0.60153422, -0.75845619, -1.09845379, -0.92845499,  2.30152223,
        -1.09845379,  0.60153422,  0.43153542],
       [-1.4236884 , -1.23089726,  0.50422298, -1.10236984,  0.24716813,
         0.43995926,  1.46817866, -1.10236984,  0.37569555, -0.07415044,
        -0.52399643,  1.1468601 ,  1.27538753],
       [-0.90072087,  0.50440368, -0.58847097, -0.58847097, -0.90072087,
        -0.43234602,  0.81665358,  1.59727833,  0.97277853, -1.21297077,
         1.75340328, -0.43234602, -0.58847097],
       [ 1.79230957,  1.31436035, -0.59743652,  1.01564209,  0.17923096,
        -0.47794922, -1.43384765,  0.83641113, -0.47794922, -0.23897461,
         0.23897461, -1.07538574, -1.07538574]])

In [206]:
r = np.corrcoef(b[:, : -1].T)
r

array([[ 1.        ,  0.22857947, -0.82413376, -0.24544511],
       [ 0.22857947,  1.        , -0.13924238, -0.972955  ],
       [-0.82413376, -0.13924238,  1.        ,  0.029537  ],
       [-0.24544511, -0.972955  ,  0.029537  ,  1.        ]])

In [207]:
md = PCA().fit(b[:, :-1])

In [208]:
md.explained_variance_

array([2.23570403e+00, 1.57606607e+00, 1.86606149e-01, 1.62374573e-03])

In [209]:
md.explained_variance_ratio_

array([5.58926009e-01, 3.94016518e-01, 4.66515373e-02, 4.05936433e-04])

In [210]:
xs = md.components_
xs

array([[-0.47595517, -0.56387024,  0.39406653,  0.54793119],
       [-0.50897938,  0.41393149,  0.60496908, -0.45123511],
       [ 0.67550019, -0.31442044,  0.63769109, -0.19542096],
       [-0.24105218, -0.64175607, -0.26846611, -0.67673402]])

In [211]:
np.cumsum(md.explained_variance_ratio_)

array([0.55892601, 0.95294253, 0.99959406, 1.        ])

In [212]:
n = 3
b[:, :-1].shape

(13, 4)

In [213]:
xs[:n, :].T.shape

(4, 3)

In [214]:
f = b[:, :-1] @ xs[:n, :].T
f.shape

(13, 3)

In [215]:
a

array([[  7. ,  26. ,   6. ,  60. ,  78.5],
       [  1. ,  29. ,  15. ,  52. ,  74.3],
       [ 11. ,  56. ,   8. ,  20. , 104.3],
       [ 11. ,  31. ,   8. ,  47. ,  87.6],
       [  7. ,  52. ,   6. ,  33. ,  95.9],
       [ 11. ,  55. ,   9. ,  22. , 109.2],
       [  3. ,  71. ,  17. ,   6. , 102.7],
       [  1. ,  31. ,  22. ,  44. ,  72.5],
       [  2. ,  54. ,  18. ,  22. ,  93.1],
       [ 21. ,  47. ,   4. ,  26. , 115.9],
       [  1. ,  40. ,  23. ,  34. ,  83.8],
       [ 11. ,  66. ,   9. ,  12. , 113.3],
       [ 10. ,  68. ,   8. ,  12. , 109.4]])

In [216]:
d2 = {
    "y": a[:, -1],
    "x": a[:, :-1]
}
d2

{'y': array([ 78.5,  74.3, 104.3,  87.6,  95.9, 109.2, 102.7,  72.5,  93.1,
        115.9,  83.8, 113.3, 109.4]),
 'x': array([[ 7., 26.,  6., 60.],
        [ 1., 29., 15., 52.],
        [11., 56.,  8., 20.],
        [11., 31.,  8., 47.],
        [ 7., 52.,  6., 33.],
        [11., 55.,  9., 22.],
        [ 3., 71., 17.,  6.],
        [ 1., 31., 22., 44.],
        [ 2., 54., 18., 22.],
        [21., 47.,  4., 26.],
        [ 1., 40., 23., 34.],
        [11., 66.,  9., 12.],
        [10., 68.,  8., 12.]])}

In [217]:
md = sm.formula.ols("y~x", d2).fit()
md.summary()

D:\Mysoftware_setup\anaconda3\envs\mypytorch\lib\site-packages\scipy\stats\_stats_py.py:1772: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=13
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.982
Model:                            OLS   Adj. R-squared:                  0.974
Method:                 Least Squares   F-statistic:                     111.5
Date:                Sun, 05 Feb 2023   Prob (F-statistic):           4.76e-07
Time:                        22:05:34   Log-Likelihood:                -26.918
No. Observations:                  13   AIC:                             63.84
Df Residuals:                       8   BIC:                             66.66
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     62.4054     70.071      0.891      0.399     -99.179     223.989
x[0]           1.5511      0.745      2.083      0.071      -0.166       3.269
x[1]           0.5102      0.724      0.705      0.501      -1.159       2.179
x[2]           0.1019      0.755      0.135      0.896      -1.638       1.842
x[3]          -0.1441      0.709     -0.203      0.844      -1.779       1.491
==============================================================================
Omnibus:                        0.165   Durbin-Watson:                   2.053
Prob(Omnibus):                  0.921   Jarque-Bera (JB):                0.320
Skew:                           0.201   Prob(JB):                        0.852
Kurtosis:                       2.345   Cond. No.                     6.06e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 6.06e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [218]:
d3 = {
    "y": a[:, -1],
    "z": f
}

In [219]:
md = sm.formula.ols("y~z", d3).fit()
md.summary()

D:\Mysoftware_setup\anaconda3\envs\mypytorch\lib\site-packages\scipy\stats\_stats_py.py:1772: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=13
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.982
Model:                            OLS   Adj. R-squared:                  0.976
Method:                 Least Squares   F-statistic:                     164.9
Date:                Sun, 05 Feb 2023   Prob (F-statistic):           3.50e-08
Time:                        22:05:34   Log-Likelihood:                -27.008
No. Observations:                  13   AIC:                             62.02
Df Residuals:                       9   BIC:                             64.28
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     95.4231      0.644    148.167      0.000      93.966      96.880
z[0]          -9.8831      0.448    -22.045      0.000     -10.897      -8.869
z[1]           0.1250      0.534      0.234      0.820      -1.083       1.333
z[2]           4.5548      1.552      2.935      0.017       1.045       8.065
==============================================================================
Omnibus:                        0.246   Durbin-Watson:                   1.943
Prob(Omnibus):                  0.884   Jarque-Bera (JB):                0.416
Skew:                           0.162   Prob(JB):                        0.812
Kurtosis:                       2.186   Cond. No.                         3.46
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [220]:
xs3 = md.params
xs3

Intercept    95.423077
z[0]         -9.883095
z[1]          0.124993
z[2]          4.554792
dtype: float64

In [221]:
xs40 = xs3[0] - sum(xs3[1:] @ xs[:n, :] * mu[:-1] / s[:-1])  #常数项
xs40

85.74326349653427

In [222]:
xs4 = xs3[1:] @ xs[:n, :] / s[:-1]  #原始变量回归方程的其他系数
xs4

array([ 1.3118899 ,  0.26941931, -0.14276535, -0.3800747 ])

In [223]:
a = pd.read_excel("data12_3.xlsx", header=None)
b = a.values
c = zscore(b, ddof=1)
md = PCA().fit(c)
md.explained_variance_

array([7.50963582e+00, 2.27720858e+00, 1.47105704e+00, 8.50786152e-01,
       6.50545056e-01, 5.06438457e-01, 3.38461134e-01, 2.41850500e-01,
       7.58718928e-02, 5.63367008e-02, 1.62614416e-02, 4.86075319e-03,
       5.75813307e-04, 1.10664593e-04])

In [224]:
r1 = md.explained_variance_ratio_
r1

array([5.36402558e-01, 1.62657756e-01, 1.05075503e-01, 6.07704394e-02,
       4.64675040e-02, 3.61741755e-02, 2.41757953e-02, 1.72750357e-02,
       5.41942091e-03, 4.02405005e-03, 1.16153155e-03, 3.47196656e-04,
       4.11295220e-05, 7.90461377e-06])

In [225]:
np.cumsum(md.explained_variance_ratio_)

array([0.53640256, 0.69906031, 0.80413582, 0.86490626, 0.91137376,
       0.94754794, 0.97172373, 0.98899877, 0.99441819, 0.99844224,
       0.99960377, 0.99995097, 0.9999921 , 1.        ])

In [226]:
xs1 = md.components_
xs1

array([[ 2.78837967e-01,  9.63690035e-02,  3.49799816e-01,
        -1.45018084e-01,  3.29817004e-01,  2.37834177e-01,
         3.08318801e-01,  3.15450966e-01,  2.52655866e-01,
         2.36263388e-01,  2.82162395e-01,  3.30220374e-01,
         2.67528231e-01,  1.72540600e-01],
       [-2.71074673e-01,  2.94888719e-01,  5.78873627e-02,
         1.02727277e-01, -7.89358305e-02, -1.96705527e-01,
         8.04817160e-02, -1.52455238e-01,  4.29775336e-01,
         4.71523096e-01,  3.25314924e-01, -1.53184629e-01,
        -1.87591528e-01, -4.23656357e-01],
       [-2.24640360e-03,  4.90196501e-01, -1.27799797e-01,
         5.75555790e-01,  4.14247284e-02,  4.71543730e-01,
         6.22191345e-02, -1.02008064e-01, -9.68328447e-02,
        -6.62680302e-02, -2.11089160e-01,  1.03482635e-01,
         2.55837732e-01, -1.98167707e-01],
       [-2.98738797e-01,  5.44463206e-01,  1.07239046e-01,
        -4.01997161e-01,  1.84903015e-01, -3.79735798e-03,
        -4.21887319e-01, -2.34448773e-01, -1.

In [227]:
n1 = 4

df1 = c @ xs1[:n1, :].T
df1.shape

(15, 4)

In [228]:
r1[:n1].shape

(4,)

In [229]:
g1 = df1 @ r1[:n1]  #计算综合评价得分
g1

array([ 0.29285016,  1.01659708, -1.22657941, -0.93647745, -1.64930206,
        0.03800517,  0.31471543,  3.28572061, -1.12046447, -0.12595321,
        0.06706603,  3.02572877, -1.50884546, -1.21366531, -0.25939588])

In [230]:
ind1 = np.argsort(-g1)
ind1

array([ 7, 11,  1,  6,  0, 10,  5,  9, 14,  3,  8, 13,  2, 12,  4],
      dtype=int64)

In [231]:
ind11 = np.zeros(15)
ind11[ind1] = np.arange(1, 16)
ind11

array([ 5.,  3., 13., 10., 15.,  7.,  4.,  1., 11.,  8.,  6.,  2., 14.,
       12.,  9.])

In [232]:
n = b.shape[0]
n

15

In [233]:
K = (1 + c @ c.T) ** 3
K

array([[ 1.29700250e+03,  2.87083705e+02, -1.09944821e+00,
        -5.45799811e+01, -6.65459544e+00,  6.88063597e+01,
         1.05856367e+02, -5.10640728e-02, -1.95570074e+02,
        -2.90625039e+00,  1.13233645e+00,  3.71084005e+02,
        -1.03207988e+02, -6.42303205e+00,  2.19450453e+00],
       [ 2.87083705e+02,  2.83073981e+03, -7.03601849e+01,
        -2.87400613e+01, -4.29373384e+02,  2.32347748e+01,
         4.00642271e+02,  3.17351519e+02, -1.77831526e+02,
        -8.69445829e+00,  2.69103124e+00,  3.49444130e+03,
        -2.65564293e+02, -3.15814989e+02, -5.07411568e+01],
       [-1.09944821e+00, -7.03601849e+01,  2.93597572e+02,
         2.13229486e+02,  2.79956262e+02,  1.49137770e-01,
        -1.92154325e+00, -1.02510254e+03,  1.53444360e+02,
         1.82111282e+00,  3.44990788e+00, -1.35782247e+03,
         4.13377452e+02,  1.78594642e+02,  4.91927732e+00],
       [-5.45799811e+01, -2.87400613e+01,  2.13229486e+02,
         4.71769120e+02,  3.94213546e+01, -3.43943498

In [234]:
J = np.ones((n, n)) / n
J

array([[0.06666667, 0.06666667, 0.06666667, 0.06666667, 0.06666667,
        0.06666667, 0.06666667, 0.06666667, 0.06666667, 0.06666667,
        0.06666667, 0.06666667, 0.06666667, 0.06666667, 0.06666667],
       [0.06666667, 0.06666667, 0.06666667, 0.06666667, 0.06666667,
        0.06666667, 0.06666667, 0.06666667, 0.06666667, 0.06666667,
        0.06666667, 0.06666667, 0.06666667, 0.06666667, 0.06666667],
       [0.06666667, 0.06666667, 0.06666667, 0.06666667, 0.06666667,
        0.06666667, 0.06666667, 0.06666667, 0.06666667, 0.06666667,
        0.06666667, 0.06666667, 0.06666667, 0.06666667, 0.06666667],
       [0.06666667, 0.06666667, 0.06666667, 0.06666667, 0.06666667,
        0.06666667, 0.06666667, 0.06666667, 0.06666667, 0.06666667,
        0.06666667, 0.06666667, 0.06666667, 0.06666667, 0.06666667],
       [0.06666667, 0.06666667, 0.06666667, 0.06666667, 0.06666667,
        0.06666667, 0.06666667, 0.06666667, 0.06666667, 0.06666667,
        0.06666667, 0.06666667, 0.06666667, 

In [235]:
Kw = K - K @ J - J @ K + J @ K @ J
val, vec = np.linalg.eig(Kw)
val

array([ 8.59350160e+04,  5.18397183e+04,  3.49538554e+03,  2.68967243e+03,
        2.07508131e+03,  1.66682709e+03,  1.40496329e+03,  7.51371594e+02,
        5.98056083e+02, -1.75455224e-12,  6.32737809e+01,  1.12394486e+02,
        2.30948199e+02,  3.82459237e+02,  3.57692083e+02])

In [236]:
r2 = val / sum(val)
r2

array([ 5.66842976e-01,  3.41944199e-01,  2.30561980e-02,  1.77415679e-02,
        1.36876133e-02,  1.09946943e-02,  9.26739308e-03,  4.95618352e-03,
        3.94488656e-03, -1.15733453e-17,  4.17365353e-04,  7.41374444e-04,
        1.52337627e-03,  2.52277060e-03,  2.35940196e-03])

In [237]:
n2 = 2
m1 = vec.max(axis=0)
m2 = vec.min(axis=0)
sgn = (-1) * (abs(m2) > m1) + (abs(m2) <= m1)
sgn

array([-1, -1, -1,  1, -1,  1, -1, -1, -1, -1,  1,  1,  1,  1,  1])

In [238]:
vec = vec * sgn
vec

array([[-7.86171899e-02, -2.95649630e-02,  7.16338594e-02,
         1.96667684e-01, -7.61127500e-02,  5.30998266e-02,
         8.27737785e-01, -3.69512486e-01,  1.02387697e-01,
         2.58198890e-01, -1.16070906e-02, -2.51652194e-02,
         5.79255721e-02, -1.87444331e-01,  4.92436079e-02],
       [-6.77314390e-02,  2.87538870e-02,  3.67084620e-01,
         6.67450772e-01,  5.10813553e-01,  1.50195132e-01,
        -2.41390841e-01,  1.63877102e-02,  1.21432890e-02,
         2.58198890e-01, -1.25378606e-02, -1.79913253e-02,
         2.12176507e-02, -9.03977643e-03,  6.70069998e-02],
       [-9.43942768e-02, -5.76741791e-02, -4.87828549e-02,
         1.99578602e-02, -5.22612576e-02, -1.92732205e-01,
         1.43436130e-03,  3.31090468e-02, -3.12324052e-01,
         2.58198890e-01, -4.19215252e-01,  7.72201174e-01,
         3.22524706e-02,  8.03116677e-02,  1.64581858e-02],
       [-8.53534273e-02, -4.58599116e-02, -3.79497110e-02,
         4.30092863e-02, -1.07292066e-01, -2.99708490

In [239]:
df2 = Kw @ (vec[:, :n2])
g2 = df2 @ r2[: n2]
ind2 = np.argsort(-g2)
ind2

array([ 7, 11,  1,  6,  0, 10,  5,  9, 14,  3,  8,  2, 13, 12,  4],
      dtype=int64)

In [240]:
ind22 = np.zeros(15)
ind22[ind2] = np.arange(1, 16)
ind22

array([ 5.,  3., 12., 10., 15.,  7.,  4.,  1., 11.,  8.,  6.,  2., 14.,
       13.,  9.])

In [241]:
r = np.array([
    [1, 1 / 5, -1 / 5],
    [1 / 5, 1, -2 / 5],
    [-1 / 5, -2 / 5, 1]
])

val, vec = np.linalg.eig(r)  #求相关系数阵的特征值和特征向量
val

array([0.85358984, 1.54641016, 0.6       ])

In [242]:
vec

array([[-8.88073834e-01,  4.59700843e-01,  2.70980663e-17],
       [ 3.25057584e-01,  6.27963030e-01,  7.07106781e-01],
       [-3.25057584e-01, -6.27963030e-01,  7.07106781e-01]])

In [243]:
A0 = vec * np.sqrt(val)  #载荷矩阵
A0

array([[-8.20490756e-01,  5.71659793e-01,  2.09900719e-17],
       [ 3.00320460e-01,  7.80901800e-01,  5.47722558e-01],
       [-3.00320460e-01, -7.80901800e-01,  5.47722558e-01]])

In [244]:
num = 2
A = A0[:, :num]
A

array([[-0.82049076,  0.57165979],
       [ 0.30032046,  0.7809018 ],
       [-0.30032046, -0.7809018 ]])

In [245]:
Ac = np.sum(A ** 2, axis=0)  #逐列元素求和，求信息贡献
Ac

array([0.85358984, 1.54641016])

In [246]:
Ar = np.sum(A ** 2, axis=1)  #逐行元素求和，求共同度
Ar

array([1. , 0.7, 0.7])

In [247]:
c = np.loadtxt("data12_5_1.txt")
d = zscore(c, ddof=1)
d

array([[ 1.22755729e+00,  1.87376856e+00,  1.01425549e+00,
         1.47323078e+00,  1.08772685e+00,  4.92033268e-01],
       [ 5.07954742e-01,  1.48164755e+00,  1.18004726e+00,
         1.01140950e+00, -7.73789428e-02,  9.75319278e-01],
       [ 9.39716272e-01,  1.22792219e+00,  1.05947143e+00,
         4.43014078e-01,  2.98461636e-01,  6.77912503e-01],
       [-1.15700802e-01,  1.08952654e+00,  9.38895601e-01,
         2.65390509e-01,  1.27564714e+00,  8.26615891e-01],
       [ 1.51539831e+00,  1.04339466e+00,  1.95049133e-02,
         4.78538792e-01,  1.12531091e+00,  6.03560809e-01],
       [ 6.99848755e-01,  2.36086697e-01,  1.05947143e+00,
         8.33785929e-01,  3.73629752e-01, -6.56044358e-02],
       [ 7.95795762e-01, -8.68364863e-02,  2.00368655e-01,
         7.62736502e-01,  9.74974679e-01,  1.01249513e+00],
       [ 3.64034231e-01, -3.63627786e-01,  1.04439945e+00,
        -8.35875618e-01, -2.21082694e-03,  1.08684682e+00],
       [ 3.16060728e-01, -1.56034311e-01, -1.161

In [248]:
r = np.corrcoef(d.T)
r

array([[1.        , 0.76868484, 0.68193448, 0.71187315, 0.84264892,
        0.72092259],
       [0.76868484, 1.        , 0.71243838, 0.68790154, 0.66910603,
        0.6414101 ],
       [0.68193448, 0.71243838, 1.        , 0.5557287 , 0.61561746,
        0.74972839],
       [0.71187315, 0.68790154, 0.5557287 , 1.        , 0.51866661,
        0.58407218],
       [0.84264892, 0.66910603, 0.61561746, 0.51866661, 1.        ,
        0.59610918],
       [0.72092259, 0.6414101 , 0.74972839, 0.58407218, 0.59610918,
        1.        ]])

In [249]:
val, vec = np.linalg.eig(r)
val

array([4.36267608, 0.10617001, 0.20667295, 0.31555211, 0.49935661,
       0.50957223])

In [250]:
vec

array([[-0.44399125, -0.80139887,  0.0381006 , -0.21107537,  0.30700032,
        -0.1427514 ],
       [-0.42031556,  0.08839598,  0.57410301,  0.67057753, -0.06970742,
        -0.17718173],
       [-0.40405356, -0.09993591, -0.59375312,  0.37315815, -0.27926047,
         0.50692933],
       [-0.37797382,  0.21495581, -0.31370398, -0.22428584, -0.42380862,
        -0.69469542],
       [-0.39837836,  0.50869063, -0.18193709, -0.07610277,  0.73664425,
         0.03148081],
       [-0.40171856,  0.18704721,  0.43000003, -0.55716262, -0.31724876,
         0.45569569]])

In [251]:
cs = np.cumsum(val)
cs

array([4.36267608, 4.46884609, 4.67551904, 4.99107115, 5.49042777,
       6.        ])

In [252]:
rate = val / cs[-1]
rate

array([0.72711268, 0.017695  , 0.03444549, 0.05259202, 0.0832261 ,
       0.08492871])

In [253]:
srate = sorted(rate, reverse=True)
srate

[0.7271126794515892,
 0.08492870573277395,
 0.08322610238668912,
 0.05259201847435394,
 0.03444549208346,
 0.017695001871133816]

In [254]:
from factor_analyzer import FactorAnalyzer as FA

In [255]:
fa = FA(n_factors=3, rotation="varimax")
fa.fit(d)
A = fa.loadings_  # 提取载荷矩阵
A

array([[0.83867689, 0.3441876 , 0.39505553],
       [0.52893897, 0.47290977, 0.43391481],
       [0.33571713, 0.91174135, 0.23162577],
       [0.31124833, 0.26406099, 0.91065183],
       [0.76907315, 0.33557201, 0.2108937 ],
       [0.45522506, 0.56945472, 0.32162593]])

In [256]:
gx = np.sum(A ** 2, axis=0)  #计算信息贡献
gx

array([1.99144024, 1.67999651, 1.37520757])

In [257]:
s2 = 1 - np.sum(A ** 2, axis=1)
s2

array([0.02208709, 0.30829785, 0.00237122, 0.00410953, 0.25144177,
       0.36504823])

In [258]:
np.diag(s2)

array([[0.02208709, 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.30829785, 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.00237122, 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.00410953, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.25144177,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.36504823]])

In [259]:
ss = np.linalg.inv(np.diag(s2))
ss

array([[ 45.27531285,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   3.24361656,   0.        ,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        , 421.72392031,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        , 243.33709316,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          3.97706398,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   2.73936409]])

In [265]:
f = ss @ A @ np.linalg.inv(A.T @ ss @ A)
f

array([[ 1.43189202, -0.43811497, -0.36071025],
       [ 0.04189832, -0.01102147, -0.00795296],
       [-0.46094053,  1.32188303, -0.22704375],
       [-0.56143968, -0.13099817,  1.32648447],
       [ 0.12336331, -0.03604826, -0.0352287 ],
       [ 0.02539619, -0.00442743, -0.0062039 ]])

In [263]:
df = d @ f
df

array([[ 0.68827692,  0.54788456,  1.22487117],
       [-0.30713848,  1.18699035,  0.87536387],
       [ 0.71397671,  0.90346555, -0.01634608],
       [-0.52343658,  1.19538191,  0.12186789],
       [ 2.09009218, -0.75556065,  0.03204037],
       [ 0.09995176,  0.96887838,  0.59838204],
       [ 0.76125634, -0.22237503,  0.63927609],
       [ 0.52123905,  1.32985872, -1.48098416],
       [-0.30726848, -0.48950852,  1.8619172 ],
       [-0.01530699,  0.11499225, -0.5966919 ],
       [-0.69527783,  0.98004269, -0.49890659],
       [-0.11080445, -0.19844714, -0.86002843],
       [ 1.4077055 , -1.31219597, -1.60404178],
       [-1.26415469, -1.20504901,  1.27145335],
       [ 0.21464754, -1.98994032,  0.24848469],
       [-1.02272362, -0.48180379, -0.58886235],
       [-2.25103488, -0.57261399, -1.22779537]])

In [ ]:
pj = df @ gx / sum(gx)
pj

In [ ]:
ind0 = np.argsort(-pj)  #从大到小的排名地址
ind = np.zeros(17)
ind[ind0] = np.arange(1, 18)
ind